// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycirkubrqgoleycnkuqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljaXJrdWJycWdvbGV5Y25rdXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5Njc1MTYsImV4cCI6MjA1MjU0MzUxNn0.lOdP8NKC0RGBUgbuK8wxyNIQyYvOAk24nfb0iHJlQ-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);